<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<Platforms>x64</Platforms>
		<AssemblyName>AudioIntel</AssemblyName>
		<RootNamespace>AudioIntel</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.0.10" />
		<PackageReference Include="Avalonia.Desktop" Version="11.0.10" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.10" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.10" />
		<PackageReference Include="CefGlue.Avalonia" Version="120.6099.207" />
		<PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.0" />
		<PackageReference Include="WebViewControl-Avalonia" Version="3.120.11" />
	</ItemGroup>
</Project>